# Generated by Django 4.2.21 on 2025-05-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0008_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('sci-fi', 'Science Fiction'), ('drama', 'Drama'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('horror', 'Horror'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
